version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: "no"
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  node:
    build: .
    ports:
    - "8080:8080"
